image: node:4.2.2

before_script:
  # Install Node dependencies
  - npm install --silent
  - git config --global user.email "dev@chialab.io"
  - git config --global user.name "GitLab CI"
  - git config --global push.default simple

stages:
  # - test
  - doc
  - deploy

# exec_test:
#   stage: test
#   script:
#     - npm run test

exec_deploy:
  stage: deploy
  only:
    - tags
  script:
    - ./scripts/deploy.sh

generate_doc:
  stage: doc
  only:
    - tags
  script:
    - ./scripts/doc.sh
