image: node:5.9.0

before_script:
  # Install Node dependencies
  - npm install --silent
  - ./scripts/config.sh

stages:
  # - test
  - doc
  - deploy

# exec_test:
#   stage: test
#   script:
#     - npm run test

exec_deploy:
  stage: deploy
  only:
    - tags
  script:
    - ./scripts/deploy.sh

exec_deploy_beta:
  stage: deploy
  only:
    - beta
  script:
    - ./scripts/deploy.sh --beta

generate_doc:
  stage: doc
  only:
    - tags
  script:
    - ./scripts/doc.sh
