language: node_js

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      env: CI_BUILD_TYPE=default
      node_js: 6
      install:
        - npm install
      script:
        - npm run test-default
    - stage: test
      env: CI_BUILD_TYPE=default
      node_js: 7
      install:
        - npm install
      script:
        - npm run test-default
    - stage: test
      os: linux
      env: CI_BUILD_TYPE=saucelabs
      node_js: 7
      install:
        - npm install
        - npm install karma-sauce-launcher
      script:
        - npm run test-saucelabs
    - stage: test
      os: linux
      env: CI_BUILD_TYPE=electron
      node_js: 7
      install:
        - export DISPLAY=':99.0'
        - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        - npm install
        - npm install electron karma-electron-launcher
      script:
        - npm run test-electron
    - stage: test
      os: osx
      env: CI_BUILD_TYPE=electron
      node_js: 7
      install:
        - export DISPLAY=':99.0'
        - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        - npm install
        - npm install electron karma-electron-launcher
      script:
        - npm run test-electron
  allow_failures:
    - env: CI_BUILD_TYPE=electron
    - env: CI_BUILD_TYPE=saucelabs

addons:
  apt:
    packages:
      - xvfb

after_success:
  - cat coverage/report-lcov/*/lcov.info | ./node_modules/.bin/codecov
