language: node_js

branches:
  only:
    - '3.0.0'

jobs:
  include:
    - stage: test
      env: CI_BUILD_TYPE=node
      node_js: 10
      before_install:
        - yarn config set registry https://registry.npmjs.org/
        - yarn add @chialab/rna-cli codecov -D
      install:
        - yarn
      script:
        - yarn test:node
      after_success:
        - cat test/__coverage__/*/lcov.info | ./node_modules/.bin/codecov
    - stage: test
      os: linux
      env: CI_BUILD_TYPE=saucelabs
      node_js: 10
      before_install:
        - yarn config set registry https://registry.npmjs.org/
        - yarn add @chialab/rna-cli codecov -D
      install:
        - yarn
      script:
        - yarn test:saucelabs
      after_success:
        - cat test/__coverage__/*/lcov.info | ./node_modules/.bin/codecov
    - stage: 'docs'
      env: CI_BUILD_TYPE=website CNAME=dna.chialab.io
      os: linux
      node_js: 10
      install:
        - pip install --user awscli
        - aws configure set preview.cloudfront true
        - yarn config set registry https://registry.npmjs.org/
        - yarn add @chialab/rna-cli -D
      script:
        - yarn
        - yarn run docs
        - yarn run website
        - ls -R public
      after_success:
        - for file in public/*.html; do mv -- "$file" "${file%%.html}"; done
        - for file in public/**/*.html; do mv -- "$file" "${file%%.html}"; done
        - aws s3 sync public s3://$CNAME/v3 --region us-east-1 --size-only --exclude "*" --include "*.*" --delete
        - aws s3 sync public s3://$CNAME/v3 --region us-east-1 --size-only --content-type text/html --exclude "*.*" --delete
        - aws cloudfront create-invalidation --paths '/*' --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?contains(Aliases.Items, '${CNAME}')].Id" --output text)
  allow_failures:
    - env: CI_BUILD_TYPE=website
