language: node_js

stages:
  - name: test
  - name: deploy
    if: repo = Chialab/dna AND branch = master AND type IN (push, api)

addons:
  apt:
    packages:
      - xvfb

env:
  global:
    - "SAUCE_USERNAME=$SAUCE_NEXT_USERNAME"
    - "SAUCE_ACCESS_KEY=$SAUCE_NEXT_ACCESS_KEY"
    - "DISPLAY=':99.0'"
    - "CHROME_BIN=chromium-browser"

jobs:
  include:
    ############
    ### Test ###
    ############
    - stage: test
      env: CI_BUILD_TYPE=default
      node_js: 6
      before_install:
        - sh -e /etc/init.d/xvfb start
      install:
        - yarn install
      script:
        - yarn test

    - stage: test
      env: CI_BUILD_TYPE=default
      node_js: 7
      before_install:
        - sh -e /etc/init.d/xvfb start
      install:
        - yarn install
      script:
        - yarn test

    - stage: test
      os: linux
      env: CI_BUILD_TYPE=saucelabs
      node_js: 7
      install:
        - yarn install
        # - yarn install karma-sauce-launcher
      script:
        - yarn run test-saucelabs

    - stage: test
      os: linux
      env: CI_BUILD_TYPE=electron
      node_js: 7
      install:
        - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        - yarn install
        # - yarn install electron karma-electron-launcher
      script:
        - yarn run test-electron

    - stage: test
      os: osx
      env: CI_BUILD_TYPE=electron
      node_js: 7
      install:
        - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        - yarn install
        # - yarn install electron karma-electron-launcher
      script:
        - yarn run test-electron

    ##############
    ### Deploy ###
    ##############
    - stage: deploy
      os: linux
      env: CI_BUILD_TYPE=docs
      node_js: 7
      install:
        - yarn install documentation
        - yarn install
        - git clone https://${GH_TOKEN}@github.com/Chialab/dna.wiki.git wiki
      before_script:
        - git config --global user.email "travis@travis-ci.org"
        - git config --global user.name "travis-ci"
      script:
        - ./node_modules/.bin/documentation build packages/core/index.js -f md > ./wiki/API.md
      after_success:
        - git -C wiki add .
        - git -C wiki diff-index --quiet HEAD || git -C wiki commit -m "Lastest api reference on successful travis build ${TRAVIS_BUILD_NUMBER} auto-pushed to wiki"
        - git -C wiki push origin

    - stage: deploy
      os: linux
      env: CI_BUILD_TYPE=website CNAME=dna.chialab.io S3_BUCKET=chialab-static-sites
      node_js: 7
      install:
        - pip install --user awscli
        - aws configure set preview.cloudfront true
        - git clone https://gitlab.com/chialab/project-pages.git pages
      before_script:
        - mkdir -p public
        - git config --global user.email "travis@travis-ci.org"
        - git config --global user.name "travis-ci"
      script:
        - yarn --cwd pages install
        - node ./pages/index.js . --extra.ga 'UA-149131-70'
        - ls -R public
      after_success:
        - for file in public/*.html; do mv -- "$file" "${file%%.html}"; done
        - for file in public/**/*.html; do mv -- "$file" "${file%%.html}"; done
        - sed -i 's/\.html//g' public/service-worker.js
        - aws s3 sync public s3://$S3_BUCKET/$CNAME/ --region eu-west-1 --size-only --exclude "*" --include "*.*" --delete
        - aws s3 sync public s3://$S3_BUCKET/$CNAME/ --region eu-west-1 --size-only --content-type text/html --exclude "*.*" --delete
        - aws cloudfront create-invalidation --paths '/*' --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?contains(Aliases.Items, '${CNAME}')].Id" --output text)

  allow_failures:
    - env: CI_BUILD_TYPE=electron
    - env: CI_BUILD_TYPE=saucelabs

after_success:
  - cat coverage/report-lcov/*/lcov.info | ./node_modules/.bin/codecov
