language: node_js

branches:
  only:
    - master

env:
  global:
    - "SAUCE_USERNAME=$SAUCE_NEXT_USERNAME"
    - "SAUCE_ACCESS_KEY=$SAUCE_NEXT_ACCESS_KEY"

jobs:
  include:
    - stage: test
      env: CI_BUILD_TYPE=default
      node_js: 10
      services:
        - xvfb
      addons:
        chrome: stable
      before_install:
        - export DISPLAY=:99.0
        - yarn config set registry https://registry.npmjs.org/
        - yarn global add @chialab/rna-cli
        - yarn global add codecov
      install:
        - yarn install
      script:
        - yarn test
      after_success:
        - cat reports/unit/coverage/*/lcov.info | codecov
    - stage: test
      os: linux
      env: CI_BUILD_TYPE=saucelabs
      node_js: 10
      before_install:
        - yarn config set registry https://registry.npmjs.org/
        - yarn global add @chialab/rna-cli
      install:
        - yarn install
      script:
        - yarn run test-saucelabs
    - stage: deploy
      os: linux
      env: CI_BUILD_TYPE=docs
      node_js: 10
      install:
        - yarn global add documentation
        - yarn install --ignore-scripts
      script:
        - git config --global user.email "travis@travis-ci.org"
        - git config --global user.name "travis-ci"
        - git clone https://${GH_TOKEN}@github.com/Chialab/dna.wiki.git wiki
        - documentation build packages/core/index.js -f md > ./wiki/API.md
        - cd wiki
        - git add .
        - git diff-index --quiet HEAD || git commit -m "Lastest api reference on successful travis build ${TRAVIS_BUILD_NUMBER} auto-pushed to wiki"
        - git push origin
  allow_failures:
    - env: CI_BUILD_TYPE=electron
    - env: CI_BUILD_TYPE=saucelabs
