language: node_js
node_js:
  - "6"

env:
  matrix:
    - "CI_BUILD_TYPE=minimum"
    - "CI_BUILD_TYPE=all"

matrix:
  allow_failures:
    - env: "CI_BUILD_TYPE=all"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

addons:
  sauce_connect: true

script:
  - if [ "$CI_BUILD_TYPE" = 'minimum' ]; then npm run test-ci; fi
  - if [ "$CI_BUILD_TYPE" = 'all' ]; then npm run test-ci; fi

after_success:
  - npm run codecov
  - npm run coveralls
