language: node_js
node_js:
  - "6"

branches:
  only:
    - master

env:
  global:
    - "SAUCE_USERNAME=$SAUCE_NEXT_USERNAME"
    - "SAUCE_ACCESS_KEY=$SAUCE_NEXT_ACCESS_KEY"
  matrix:
    - "CI_BUILD_TYPE=default"
    - "CI_BUILD_TYPE=saucelabs"

matrix:
  allow_failures:
    - env: "CI_BUILD_TYPE=saucelabs"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

addons:
  sauce_connect:
    no_ssl_bump_domains: all

script:
  - npm test

after_success:
  - if [ "$CI_BUILD_TYPE" = 'saucelabs' ]; then cat coverage/report-lcov/*/lcov.info | ./node_modules/.bin/codecov; fi
