branches:
  only:
    - '3.0.0'

jobs:
  include:
    - stage: 'docs'
      env: CI_BUILD_TYPE=website CNAME=dna.chialab.io S3_BUCKET=chialab-static-sites
      os: linux
      node_js: 12
      install:
        - pip install --user awscli
        - aws configure set preview.cloudfront true
        - yarn global add @chialab/rna-cli
      script:
        - yarn
        - yarn run docs
        - yarn run website
        - ls -R public
      after_success:
        - for file in public/*.html; do mv -- "$file" "${file%%.html}"; done
        - for file in public/**/*.html; do mv -- "$file" "${file%%.html}"; done
        - aws s3 sync public s3://$S3_BUCKET/$CNAME/v3 --region eu-west-1 --size-only --exclude "*" --include "*.*" --delete
        - aws s3 sync public s3://$S3_BUCKET/$CNAME/v3 --region eu-west-1 --size-only --content-type text/html --exclude "*.*" --delete
        - aws cloudfront create-invalidation --paths '/*' --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?contains(Aliases.Items, '${CNAME}')].Id" --output text)
  allow_failures:
    - env: CI_BUILD_TYPE=website
