name: BrowserStack
on:
  workflow_dispatch:

jobs:
  test-browserstack:
    name: Test Browserstack
    runs-on: ubuntu-latest
    concurrency: browserstack
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: yarn

      - name: Install project dependencies
        run: yarn install
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true

      - name: Run tests
        run: yarn test:browserstack
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
