name: Build
on: push

env:
  NPM_REGISTRY_URL: https://registry.npmjs.org/

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
        with:
          ref: '3.0.0'
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Config Yarn cache
        run: yarn config set cache-folder $GITHUB_WORKSPACE/.yarn
      - name: Set up Yarn cache
        uses: actions/cache@v1
        with:
          path: .yarn
          key: yarn-cache-${{ runner.OS }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install RNA
        run: yarn add @chialab/rna-cli
      - name: Install project dependencies
        run: yarn install
      - name: Run build script
        run: yarn run build
      - name: Upload distribution files
        uses: actions/upload-artifact@v1
        with:
          name: DNA
          path: dist
