name: Docs
on: push

jobs:
  api:
    name: API references
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Config Yarn cache
        run: yarn config set cache-folder $GITHUB_WORKSPACE/.yarn
      - name: Set up Yarn cache
        uses: actions/cache@v1
        with:
          path: .yarn
          key: yarn-cache-${{ runner.OS }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install RNA
        run: npm install -g @chialab/rna-cli
      - name: Install project dependencies
        run: yarn install
      - name: Checkout the wiki
        uses: actions/checkout@v1
        with:
          repository: chialab/dna.wiki
          ref: ${{ github.ref }}
          path: 'wiki'
          token: ${{ secrets.GITHUB_WIKI_TOKEN }}
      - name: Generate API references
        run: rna documentate --output wiki/API.md --header '# API References'
      - name: Push API references
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_WIKI_TOKEN }}
        run: |
          git config --global user.email "dev@chialab.io"
          git config --global user.name "chialab-io"
          git -C wiki add .
          git -C wiki diff-index --quiet HEAD || git -C wiki commit -m "Lastest api reference ${GITHUB_REF#refs/heads/} auto-pushed to wiki"
          git -C wiki push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/chialab/dna.wiki.git" HEAD:${GITHUB_REF#refs/heads/} --follow-tags --force
