name: Lint and Test
on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Install project dependencies
        run: yarn install
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true

      - name: Run build script
        run: yarn build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DNA
          path: |
            dist
            types

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Install project dependencies
        run: yarn install
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true

      - name: Fetch build artifacts
        uses: actions/download-artifact@v3
        with:
          name: DNA

      - name: Lint
        run: yarn lint

  test-browser:
    name: Test Browsers
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Install project dependencies
        run: yarn install

      - name: Fetch build artifacts
        uses: actions/download-artifact@v3
        with:
          name: DNA

      - name: Run tests
        run: yarn test:browser

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage/lcov.info

  test-node:
    name: Test Node
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Install project dependencies
        run: yarn install
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true

      - name: Fetch build artifacts
        uses: actions/download-artifact@v3
        with:
          name: DNA

      - name: Run tests
        run: yarn test:node

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage/lcov.info

  test-saucelabs:
    name: Test SauceLabs
    runs-on: ubuntu-latest
    needs: build
    concurrency: saucelabs
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Install project dependencies
        run: yarn install
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true

      - name: Fetch build artifacts
        uses: actions/download-artifact@v3
        with:
          name: DNA

      - name: Run tests
        run: yarn test:saucelabs
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
