name: Pull Request
on:
  pull_request:
    types: [opened, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-build-test:
    uses: ./.github/workflows/lint_build_test.yml
    secrets: inherit

  test-browserstack:
    name: Test Browserstack
    runs-on: ubuntu-latest
    concurrency: browserstack
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: pnpm
      - name: Install project dependencies
        run: pnpm install
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
      - name: Run tests
        run: pnpm test:browserstack
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
