name: Test
on: push

jobs:
  test-node:
    name: Test Node
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Config Yarn cache
        run: yarn config set cache-folder $GITHUB_WORKSPACE/.yarn
      - name: Set up Yarn cache
        uses: actions/cache@v1
        with:
          path: .yarn
          key: yarn-cache-${{ runner.OS }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install RNA
        run: npm install -g @chialab/rna-cli
      - name: Install project dependencies
        run: yarn install
      - name: Run tests
        run: yarn run test:node
      - name: Upload coverage files
        uses: actions/upload-artifact@v1
        with:
          name: Coverage
          path: test/__coverage__
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: test/__coverage__/*/lcov.info
  test-saucelabs:
    name: Test SauceLabs
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Config Yarn cache
        run: yarn config set cache-folder $GITHUB_WORKSPACE/.yarn
      - name: Set up Yarn cache
        uses: actions/cache@v1
        with:
          path: .yarn
          key: yarn-cache-${{ runner.OS }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install RNA
        run: npm install -g @chialab/rna-cli
      - name: Install project dependencies
        run: yarn install
      - name: Run tests
        run: yarn run test:saucelabs
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      - name: Upload coverage files
        uses: actions/upload-artifact@v1
        with:
          name: Coverage
          path: test/__coverage__
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: test/__coverage__/*/lcov.info
